//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorway_Studio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doorway_Studio.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;#TITLE#&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;ul&gt;
        ///[MAPBLOCK]&lt;li&gt;&lt;a href=&quot;[MAPLINK]&quot;&gt;[MAPBKEYWORD]&lt;/a&gt;&lt;/li&gt;[/MAPBLOCK]
        ///&lt;/ul&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string AutoMap {
            get {
                return ResourceManager.GetString("AutoMap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Computer {
            get {
                object obj = ResourceManager.GetObject("Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import {
            get {
                object obj = ResourceManager.GetObject("Import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Item {
            get {
                object obj = ResourceManager.GetObject("Item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Languages {
            get {
                object obj = ResourceManager.GetObject("Languages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mail {
            get {
                object obj = ResourceManager.GetObject("Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ok {
            get {
                object obj = ResourceManager.GetObject("Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PaintBrush {
            get {
                object obj = ResourceManager.GetObject("PaintBrush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///$key = &quot;&quot;;
        ///
        ///if(!isset($_GET[&apos;page&apos;]) &amp;&amp; !isset($_GET[&apos;category&apos;]) &amp;&amp; !isset($_GET[&apos;spage&apos;]) &amp;&amp; !isset($_GET[&apos;index&apos;]) &amp;&amp; !isset($_GET[&apos;category&apos;]) &amp;&amp; !isset($_GET[&apos;sitemap&apos;]) &amp;&amp; !isset($_GET[&apos;custom&apos;]))
        ///{
        ///	$key = &quot;index&quot;;
        ///}
        ///else
        ///{
        ///	if(isset($_GET[&apos;page&apos;]))
        ///	{
        ///		$number = $_GET[&apos;page&apos;];
        ///		$key = &quot;page-&quot;.$number;
        ///	}
        ///	else if(isset($_GET[&apos;category&apos;]))
        ///	{
        ///		$number = $_GET[&apos;category&apos;];
        ///		$key = &quot;category-&quot;.$number;
        ///	}
        ///	else if(isset($_GET[&apos;spage&apos;]))
        ///	{
        ///		$number = $_GET[&apos;spage&apos;];
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPSQLite {
            get {
                return ResourceManager.GetString("PHPSQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///if(!isset($_GET[&apos;[PAGE]&apos;]) &amp;&amp; !isset($_GET[&apos;[CATEGORY]&apos;]) &amp;&amp; !isset($_GET[&apos;[STATICPAGE]&apos;]) &amp;&amp; !isset($_GET[&apos;[INDECXONTINUE]&apos;]) &amp;&amp; !isset($_GET[&apos;[CATEGORYCONTINUE1]&apos;]) &amp;&amp; !isset($_GET[&apos;sitemap&apos;]) &amp;&amp; !isset($_GET[&apos;custom&apos;]))
        ///{
        ///	include(&quot;index.txt&quot;);
        ///}
        ///else
        ///{
        ///	if(isset($_GET[&apos;[PAGE]&apos;]))
        ///	{
        ///		$number = $_GET[&apos;[PAGE]&apos;];
        ///		include(&quot;[PAGE]-&quot;.$number.&quot;.txt&quot;);
        ///	}
        ///	else if(isset($_GET[&apos;[CATEGORY]&apos;]))
        ///	{
        ///		$number = $_GET[&apos;[CATEGORY]&apos;];
        ///		include(&quot;[CATEGORY]-&quot;.$number.&quot;.txt&quot;);
        ///	}
        ///	else if(isse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PHPText {
            get {
                return ResourceManager.GetString("PHPText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Presets {
            get {
                object obj = ResourceManager.GetObject("Presets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallDone {
            get {
                object obj = ResourceManager.GetObject("SmallDone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallNew {
            get {
                object obj = ResourceManager.GetObject("SmallNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallPause {
            get {
                object obj = ResourceManager.GetObject("SmallPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallRunning {
            get {
                object obj = ResourceManager.GetObject("SmallRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallStop {
            get {
                object obj = ResourceManager.GetObject("SmallStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallUp {
            get {
                object obj = ResourceManager.GetObject("SmallUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Statistic {
            get {
                object obj = ResourceManager.GetObject("Statistic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///body {color: black;margin-left:0px;margin-top:0px}
        ///a:link{font-family:Verdana;font-size:1.2em;color: #3366cc;text-decoration: underline;font-weight: bold;}
        ///a:visited {font-family: Verdana;font-size:1.2em;color: #3366cc;text-decoration: underline;font-weight: bold}
        ///a:hover {font-family:Verdana;font-size:1.2em;color:#003399;text-d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Template {
            get {
                object obj = ResourceManager.GetObject("Template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Update {
            get {
                object obj = ResourceManager.GetObject("Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkSpace {
            get {
                object obj = ResourceManager.GetObject("WorkSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
